import type { Project, Application, FreelancerProfile } from "@/types";

export const mockProjects: Project[] = [
  {
    id: "proj-001",
    title: "핀테크 모바일 앱 백엔드 개발",
    description:
      "간편 송금 및 자산 관리 기능을 갖춘 핀테크 앱의 백엔드 API를 개발합니다. Node.js 기반의 마이크로서비스 아키텍처를 설계하고 구현합니다.",
    clientName: "페이브릿지",
    projectType: "backend",
    workType: "remote",
    status: "recruiting",
    techStack: ["Node.js", "TypeScript", "PostgreSQL", "Redis", "Docker"],
    budget: { min: 600, max: 800, currency: "KRW" },
    duration: { startDate: "2026-03-01", endDate: "2026-08-31" },
    deadline: "2026-02-25",
    headcount: 2,
    requirements: [
      "Node.js 백엔드 개발 5년 이상",
      "PostgreSQL 실무 경험",
      "금융 도메인 경험 우대",
    ],
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-02-10T09:00:00Z",
  },
  {
    id: "proj-002",
    title: "이커머스 플랫폼 풀스택 개발",
    description:
      "중소기업 대상 B2B 이커머스 플랫폼의 신규 기능 개발 및 유지보수를 담당합니다. React 프론트엔드와 Spring Boot 백엔드로 구성된 프로젝트입니다.",
    clientName: "커머스링크",
    projectType: "fullstack",
    workType: "hybrid",
    status: "recruiting",
    techStack: ["React", "TypeScript", "Spring Boot", "MySQL", "AWS"],
    budget: { min: 500, max: 700, currency: "KRW" },
    duration: { startDate: "2026-03-15", endDate: "2026-09-14" },
    deadline: "2026-03-05",
    headcount: 3,
    location: "서울 강남구",
    requirements: [
      "React 및 TypeScript 3년 이상",
      "Spring Boot 실무 경험",
      "AWS 클라우드 경험",
    ],
    createdAt: "2026-02-12T10:30:00Z",
    updatedAt: "2026-02-12T10:30:00Z",
  },
  {
    id: "proj-003",
    title: "헬스케어 iOS/Android 앱 개발",
    description:
      "건강 데이터 수집 및 분석 기능이 포함된 헬스케어 모바일 앱을 React Native로 개발합니다.",
    clientName: "헬스온",
    projectType: "mobile",
    workType: "remote",
    status: "in_progress",
    techStack: ["React Native", "TypeScript", "GraphQL", "Firebase"],
    budget: { min: 550, max: 750, currency: "KRW" },
    duration: { startDate: "2026-01-15", endDate: "2026-07-14" },
    deadline: "2026-01-10",
    headcount: 2,
    requirements: [
      "React Native 3년 이상",
      "iOS/Android 배포 경험",
      "헬스케어 도메인 우대",
    ],
    createdAt: "2026-01-05T11:00:00Z",
    updatedAt: "2026-01-05T11:00:00Z",
  },
  {
    id: "proj-004",
    title: "AI 기반 고객 서비스 챗봇 개발",
    description:
      "LLM 기반의 고객 응대 챗봇 시스템을 구축합니다. OpenAI API를 활용하여 자연스러운 대화 흐름을 구현합니다.",
    clientName: "테크서비스코",
    projectType: "backend",
    workType: "remote",
    status: "recruiting",
    techStack: ["Python", "FastAPI", "OpenAI", "PostgreSQL", "Redis"],
    budget: { min: 650, max: 900, currency: "KRW" },
    duration: { startDate: "2026-04-01", endDate: "2026-09-30" },
    deadline: "2026-03-20",
    headcount: 1,
    requirements: [
      "Python 백엔드 개발 4년 이상",
      "LLM/OpenAI API 활용 경험",
      "FastAPI 실무 경험",
    ],
    createdAt: "2026-02-15T14:00:00Z",
    updatedAt: "2026-02-15T14:00:00Z",
  },
  {
    id: "proj-005",
    title: "대시보드 웹 앱 UI/UX 개발",
    description:
      "실시간 데이터 시각화 대시보드를 개발합니다. Next.js와 D3.js를 활용한 인터랙티브 차트와 통계 화면을 구현합니다.",
    clientName: "데이터비전",
    projectType: "web",
    workType: "hybrid",
    status: "recruiting",
    techStack: ["Next.js", "TypeScript", "D3.js", "Tailwind CSS", "Supabase"],
    budget: { min: 450, max: 600, currency: "KRW" },
    duration: { startDate: "2026-03-10", endDate: "2026-07-09" },
    deadline: "2026-03-01",
    headcount: 2,
    location: "서울 마포구",
    requirements: [
      "Next.js 프론트엔드 3년 이상",
      "데이터 시각화 경험 (D3.js 또는 Chart.js)",
      "Tailwind CSS 능숙",
    ],
    createdAt: "2026-02-16T09:00:00Z",
    updatedAt: "2026-02-16T09:00:00Z",
  },
];

export const mockApplications: Application[] = [
  {
    id: "app-001",
    projectId: "proj-001",
    projectTitle: "핀테크 모바일 앱 백엔드 개발",
    freelancerId: "user-001",
    status: "reviewing",
    coverLetter: "5년 이상의 Node.js 백엔드 개발 경험을 보유하고 있습니다.",
    expectedRate: 700,
    appliedAt: "2026-02-11T10:00:00Z",
    updatedAt: "2026-02-13T15:00:00Z",
  },
  {
    id: "app-002",
    projectId: "proj-005",
    projectTitle: "대시보드 웹 앱 UI/UX 개발",
    freelancerId: "user-001",
    status: "pending",
    coverLetter: "Next.js와 데이터 시각화 경험을 갖추고 있습니다.",
    expectedRate: 550,
    appliedAt: "2026-02-17T14:00:00Z",
    updatedAt: "2026-02-17T14:00:00Z",
  },
  {
    id: "app-003",
    projectId: "proj-003",
    projectTitle: "헬스케어 iOS/Android 앱 개발",
    freelancerId: "user-001",
    status: "accepted",
    coverLetter: "React Native로 헬스케어 앱을 개발한 경험이 있습니다.",
    expectedRate: 650,
    appliedAt: "2026-01-06T09:00:00Z",
    updatedAt: "2026-01-08T11:00:00Z",
  },
];

export const mockProfile: FreelancerProfile = {
  id: "user-001",
  name: "김민준",
  email: "minjun.kim@example.com",
  phone: "010-1234-5678",
  avatarUrl: undefined,
  headline: "풀스택 개발자 | Next.js · Node.js · TypeScript",
  bio: "7년 경력의 풀스택 개발자입니다. 스타트업부터 대기업까지 다양한 규모의 프로젝트를 경험했으며, 클린 코드와 사용자 경험을 중시합니다.",
  techStack: [
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "PostgreSQL",
    "Redis",
    "Docker",
    "AWS",
    "GraphQL",
    "Tailwind CSS",
  ],
  careers: [
    {
      id: "career-001",
      company: "테크스타트업",
      role: "시니어 풀스택 개발자",
      startDate: "2022-03",
      isCurrent: true,
      description:
        "SaaS 플랫폼 개발 및 아키텍처 설계. Next.js + Node.js 기반 서비스 구축.",
      techStack: ["Next.js", "Node.js", "TypeScript", "PostgreSQL"],
    },
    {
      id: "career-002",
      company: "이커머스코리아",
      role: "풀스택 개발자",
      startDate: "2019-07",
      endDate: "2022-02",
      isCurrent: false,
      description:
        "이커머스 플랫폼 프론트엔드/백엔드 개발 및 성능 최적화 작업.",
      techStack: ["React", "Spring Boot", "MySQL", "AWS"],
    },
    {
      id: "career-003",
      company: "웹에이전시",
      role: "프론트엔드 개발자",
      startDate: "2017-09",
      endDate: "2019-06",
      isCurrent: false,
      description: "다양한 기업 웹사이트 및 랜딩 페이지 개발.",
      techStack: ["React", "Vue.js", "JavaScript", "CSS"],
    },
  ],
  availabilityStatus: "available",
  experienceYears: 7,
  kakaoId: "minjun_dev",
  createdAt: "2024-01-15T09:00:00Z",
  updatedAt: "2026-02-01T10:00:00Z",
};

export const mockNotices = [
  {
    id: "notice-001",
    title: "2026년 2월 신규 프리랜서 모집 안내",
    content:
      "테크밋에서 2월 신규 프리랜서 회원을 모집합니다. 기술 심사 후 정식 등록됩니다.",
    createdAt: "2026-02-01T09:00:00Z",
    isImportant: true,
  },
  {
    id: "notice-002",
    title: "알림톡 서비스 개선 안내",
    content:
      "카카오 알림톡 메시지 형식이 개선되었습니다. 프로젝트 알림을 더욱 빠르게 받으실 수 있습니다.",
    createdAt: "2026-02-10T14:00:00Z",
    isImportant: false,
  },
];
